### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by hubb22** [adefossez/seewav#3]
I'm under macOS 10.15 with all the requeriments installed, I'm getting this errors when encoding a file:

seewav -c 46,26,71 -W 1920 -H 1080 /Volumes/Producción\ HD/mp3/Miss\ Kittin.mp3 /Volumes/Producción\ HD/mp4 
Generating the frames...
100%|████████████████████████████| 162738/162738 [5:23:52<00:00,  8.37 frames/s]
Encoding the animation video... 
Traceback (most recent call last):
  File "/usr/local/bin/seewav", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/seewav.py", line 285, in main
    visualize(args.audio,
  File "/usr/local/lib/python3.10/site-packages/seewav.py", line 219, in visualize
    sp.run([
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffmpeg', '-y', '-loglevel', 'panic', '-r', '60', '-f', 'image2', '-s', '1920x1080', '-i', '%06d.png', '-i', PosixPath('/Volumes/Producción HD/mp3/Miss Kittin.mp3'), '-t', '2712.3133333333335', '-c:a', 'aac', '-vcodec', 'libx264', '-crf', '10', '-pix_fmt', 'yuv420p', '-shortest', PosixPath('/Volumes/Producción HD/mp4')]' returned non-zero exit status 1.

**Comment by adefossez** [comment]
Hey @hubb22, could you try saving the seewav.py file in this repo somewhere, and comment out this line: https://github.com/adefossez/seewav/blob/master/seewav.py#L76 and then run the custom version using `python3 ./seewav.py ...` from the folder where you saved it. This should print more detailed error messages.

**Comment by hubb22** [comment]
Thanks for the suggestion, these are the results after displaying the full log:

```
python3 ./seewav_log.py -c 46,26,71 -W 1920 -H 1080 /Volumes/Producción\ HD/mp3/Miss\ Kittin.mp3 /Volumes/Producción\ HD/mp4
Generating the frames...
100%|████████████████████████████| 162738/162738 [4:36:47<00:00,  9.80 frames/s]
Encoding the animation video... 
Traceback (most recent call last):
  File "/Users/jose/Desktop/seewav_log.py", line 302, in <module>
    main()
  File "/Users/jose/Desktop/seewav_log.py", line 285, in main
    visualize(args.audio,
  File "/Users/jose/Desktop/seewav_log.py", line 219, in visualize
    sp.run([
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffmpeg', '-y', '-loglevel', 'panic', '-r', '60', '-f', 'image2', '-s', '1920x1080', '-i', '%06d.png', '-i', PosixPath('/Volumes/Producción HD/mp3/Miss Kittin.mp3'), '-t', '2712.3133333333335', '-c:a', 'aac', '-vcodec', 'libx264', '-crf', '10', '-pix_fmt', 'yuv420p', '-shortest', PosixPath('/Volumes/Producción HD/mp4')]' returned non-zero exit status 1.
```

At some point it stopped working after a computer reboot, but there was no changes of versions or configurations in between.
